server:
  port: 8081
spring:
  redis:
    host: 47.99.111.49

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.111.49:3306/shengge?charset=utf8mb4&serverTimezone=UTC
    username: root
    password: root


  jpa:
    show-sql: true
